//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Web_client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Account", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class DTO_Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int zipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_date {
            get {
                return this.create_dateField;
            }
            set {
                if ((this.create_dateField.Equals(value) != true)) {
                    this.create_dateField = value;
                    this.RaisePropertyChanged("create_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street {
            get {
                return this.streetField;
            }
            set {
                if ((object.ReferenceEquals(this.streetField, value) != true)) {
                    this.streetField = value;
                    this.RaisePropertyChanged("street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int zip {
            get {
                return this.zipField;
            }
            set {
                if ((this.zipField.Equals(value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Customer", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class DTO_Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountIDField, value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupIDField, value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_SMS", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class DTO_SMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlphabetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alphabet {
            get {
                return this.AlphabetField;
            }
            set {
                if ((object.ReferenceEquals(this.AlphabetField, value) != true)) {
                    this.AlphabetField = value;
                    this.RaisePropertyChanged("Alphabet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Index {
            get {
                return this.IndexField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexField, value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sent {
            get {
                return this.SentField;
            }
            set {
                if ((object.ReferenceEquals(this.SentField, value) != true)) {
                    this.SentField = value;
                    this.RaisePropertyChanged("Sent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Schedule", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class DTO_Schedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMS_infoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountIDField, value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMS_info {
            get {
                return this.SMS_infoField;
            }
            set {
                if ((object.ReferenceEquals(this.SMS_infoField, value) != true)) {
                    this.SMS_infoField = value;
                    this.RaisePropertyChanged("SMS_info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Group", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class DTO_Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Group_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountIDField, value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group_Name {
            get {
                return this.Group_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Group_NameField, value) != true)) {
                    this.Group_NameField = value;
                    this.RaisePropertyChanged("Group_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_SMS_Template", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class DTO_SMS_Template : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMS_TemplateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMS_Template {
            get {
                return this.SMS_TemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.SMS_TemplateField, value) != true)) {
                    this.SMS_TemplateField = value;
                    this.RaisePropertyChanged("SMS_Template");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDesktopEndpoint")]
    public interface IDesktopEndpoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Insert", ReplyAction="http://tempuri.org/IDesktopEndpoint/InsertResponse")]
        bool Insert(SMS_Web_client.ServiceReference1.DTO_Account Account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Insert", ReplyAction="http://tempuri.org/IDesktopEndpoint/InsertResponse")]
        System.Threading.Tasks.Task<bool> InsertAsync(SMS_Web_client.ServiceReference1.DTO_Account Account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Update", ReplyAction="http://tempuri.org/IDesktopEndpoint/UpdateResponse")]
        bool Update(SMS_Web_client.ServiceReference1.DTO_Account Account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Update", ReplyAction="http://tempuri.org/IDesktopEndpoint/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(SMS_Web_client.ServiceReference1.DTO_Account Account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/RandomID", ReplyAction="http://tempuri.org/IDesktopEndpoint/RandomIDResponse")]
        string RandomID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/RandomID", ReplyAction="http://tempuri.org/IDesktopEndpoint/RandomIDResponse")]
        System.Threading.Tasks.Task<string> RandomIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/CheckSignin", ReplyAction="http://tempuri.org/IDesktopEndpoint/CheckSigninResponse")]
        bool CheckSignin(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/CheckSignin", ReplyAction="http://tempuri.org/IDesktopEndpoint/CheckSigninResponse")]
        System.Threading.Tasks.Task<bool> CheckSigninAsync(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/GetID", ReplyAction="http://tempuri.org/IDesktopEndpoint/GetIDResponse")]
        string GetID(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/GetID", ReplyAction="http://tempuri.org/IDesktopEndpoint/GetIDResponse")]
        System.Threading.Tasks.Task<string> GetIDAsync(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/GetName", ReplyAction="http://tempuri.org/IDesktopEndpoint/GetNameResponse")]
        string GetName(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/GetName", ReplyAction="http://tempuri.org/IDesktopEndpoint/GetNameResponse")]
        System.Threading.Tasks.Task<string> GetNameAsync(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/load_Customer", ReplyAction="http://tempuri.org/IDesktopEndpoint/load_CustomerResponse")]
        SMS_Web_client.ServiceReference1.DTO_Customer[] load_Customer(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/load_Customer", ReplyAction="http://tempuri.org/IDesktopEndpoint/load_CustomerResponse")]
        System.Threading.Tasks.Task<SMS_Web_client.ServiceReference1.DTO_Customer[]> load_CustomerAsync(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Insert_Customer", ReplyAction="http://tempuri.org/IDesktopEndpoint/Insert_CustomerResponse")]
        bool Insert_Customer(SMS_Web_client.ServiceReference1.DTO_Customer _Cus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Insert_Customer", ReplyAction="http://tempuri.org/IDesktopEndpoint/Insert_CustomerResponse")]
        System.Threading.Tasks.Task<bool> Insert_CustomerAsync(SMS_Web_client.ServiceReference1.DTO_Customer _Cus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Delete_Customer", ReplyAction="http://tempuri.org/IDesktopEndpoint/Delete_CustomerResponse")]
        bool Delete_Customer(SMS_Web_client.ServiceReference1.DTO_Customer _Cus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Delete_Customer", ReplyAction="http://tempuri.org/IDesktopEndpoint/Delete_CustomerResponse")]
        System.Threading.Tasks.Task<bool> Delete_CustomerAsync(SMS_Web_client.ServiceReference1.DTO_Customer _Cus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Update_Customer", ReplyAction="http://tempuri.org/IDesktopEndpoint/Update_CustomerResponse")]
        bool Update_Customer(SMS_Web_client.ServiceReference1.DTO_Customer _Cus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Update_Customer", ReplyAction="http://tempuri.org/IDesktopEndpoint/Update_CustomerResponse")]
        System.Threading.Tasks.Task<bool> Update_CustomerAsync(SMS_Web_client.ServiceReference1.DTO_Customer _Cus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/RandomID_Customer", ReplyAction="http://tempuri.org/IDesktopEndpoint/RandomID_CustomerResponse")]
        string RandomID_Customer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/RandomID_Customer", ReplyAction="http://tempuri.org/IDesktopEndpoint/RandomID_CustomerResponse")]
        System.Threading.Tasks.Task<string> RandomID_CustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/SMSID", ReplyAction="http://tempuri.org/IDesktopEndpoint/SMSIDResponse")]
        string SMSID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/SMSID", ReplyAction="http://tempuri.org/IDesktopEndpoint/SMSIDResponse")]
        System.Threading.Tasks.Task<string> SMSIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/SendSMS", ReplyAction="http://tempuri.org/IDesktopEndpoint/SendSMSResponse")]
        bool SendSMS(SMS_Web_client.ServiceReference1.DTO_SMS sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/SendSMS", ReplyAction="http://tempuri.org/IDesktopEndpoint/SendSMSResponse")]
        System.Threading.Tasks.Task<bool> SendSMSAsync(SMS_Web_client.ServiceReference1.DTO_SMS sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Load_Schedule", ReplyAction="http://tempuri.org/IDesktopEndpoint/Load_ScheduleResponse")]
        SMS_Web_client.ServiceReference1.DTO_Schedule[] Load_Schedule();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Load_Schedule", ReplyAction="http://tempuri.org/IDesktopEndpoint/Load_ScheduleResponse")]
        System.Threading.Tasks.Task<SMS_Web_client.ServiceReference1.DTO_Schedule[]> Load_ScheduleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Insert_Schedule", ReplyAction="http://tempuri.org/IDesktopEndpoint/Insert_ScheduleResponse")]
        bool Insert_Schedule(SMS_Web_client.ServiceReference1.DTO_Schedule _sch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Insert_Schedule", ReplyAction="http://tempuri.org/IDesktopEndpoint/Insert_ScheduleResponse")]
        System.Threading.Tasks.Task<bool> Insert_ScheduleAsync(SMS_Web_client.ServiceReference1.DTO_Schedule _sch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Delete_Schedule", ReplyAction="http://tempuri.org/IDesktopEndpoint/Delete_ScheduleResponse")]
        bool Delete_Schedule(SMS_Web_client.ServiceReference1.DTO_Schedule _sch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Delete_Schedule", ReplyAction="http://tempuri.org/IDesktopEndpoint/Delete_ScheduleResponse")]
        System.Threading.Tasks.Task<bool> Delete_ScheduleAsync(SMS_Web_client.ServiceReference1.DTO_Schedule _sch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Update_Schedule", ReplyAction="http://tempuri.org/IDesktopEndpoint/Update_ScheduleResponse")]
        bool Update_Schedule(SMS_Web_client.ServiceReference1.DTO_Schedule _sch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Update_Schedule", ReplyAction="http://tempuri.org/IDesktopEndpoint/Update_ScheduleResponse")]
        System.Threading.Tasks.Task<bool> Update_ScheduleAsync(SMS_Web_client.ServiceReference1.DTO_Schedule _sch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/RandomID_Schedule", ReplyAction="http://tempuri.org/IDesktopEndpoint/RandomID_ScheduleResponse")]
        string RandomID_Schedule();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/RandomID_Schedule", ReplyAction="http://tempuri.org/IDesktopEndpoint/RandomID_ScheduleResponse")]
        System.Threading.Tasks.Task<string> RandomID_ScheduleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Load_Group", ReplyAction="http://tempuri.org/IDesktopEndpoint/Load_GroupResponse")]
        SMS_Web_client.ServiceReference1.DTO_Group[] Load_Group(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Load_Group", ReplyAction="http://tempuri.org/IDesktopEndpoint/Load_GroupResponse")]
        System.Threading.Tasks.Task<SMS_Web_client.ServiceReference1.DTO_Group[]> Load_GroupAsync(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Insert_Group", ReplyAction="http://tempuri.org/IDesktopEndpoint/Insert_GroupResponse")]
        bool Insert_Group(SMS_Web_client.ServiceReference1.DTO_Group _group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Insert_Group", ReplyAction="http://tempuri.org/IDesktopEndpoint/Insert_GroupResponse")]
        System.Threading.Tasks.Task<bool> Insert_GroupAsync(SMS_Web_client.ServiceReference1.DTO_Group _group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Delete_Group", ReplyAction="http://tempuri.org/IDesktopEndpoint/Delete_GroupResponse")]
        bool Delete_Group(SMS_Web_client.ServiceReference1.DTO_Group _group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Delete_Group", ReplyAction="http://tempuri.org/IDesktopEndpoint/Delete_GroupResponse")]
        System.Threading.Tasks.Task<bool> Delete_GroupAsync(SMS_Web_client.ServiceReference1.DTO_Group _group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Update_Group", ReplyAction="http://tempuri.org/IDesktopEndpoint/Update_GroupResponse")]
        bool Update_Group(SMS_Web_client.ServiceReference1.DTO_Group _group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Update_Group", ReplyAction="http://tempuri.org/IDesktopEndpoint/Update_GroupResponse")]
        System.Threading.Tasks.Task<bool> Update_GroupAsync(SMS_Web_client.ServiceReference1.DTO_Group _group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/RandomID_Group", ReplyAction="http://tempuri.org/IDesktopEndpoint/RandomID_GroupResponse")]
        string RandomID_Group();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/RandomID_Group", ReplyAction="http://tempuri.org/IDesktopEndpoint/RandomID_GroupResponse")]
        System.Threading.Tasks.Task<string> RandomID_GroupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Load_Template", ReplyAction="http://tempuri.org/IDesktopEndpoint/Load_TemplateResponse")]
        SMS_Web_client.ServiceReference1.DTO_SMS_Template[] Load_Template(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Load_Template", ReplyAction="http://tempuri.org/IDesktopEndpoint/Load_TemplateResponse")]
        System.Threading.Tasks.Task<SMS_Web_client.ServiceReference1.DTO_SMS_Template[]> Load_TemplateAsync(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Insert_Template", ReplyAction="http://tempuri.org/IDesktopEndpoint/Insert_TemplateResponse")]
        bool Insert_Template(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Insert_Template", ReplyAction="http://tempuri.org/IDesktopEndpoint/Insert_TemplateResponse")]
        System.Threading.Tasks.Task<bool> Insert_TemplateAsync(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Delete_Template", ReplyAction="http://tempuri.org/IDesktopEndpoint/Delete_TemplateResponse")]
        bool Delete_Template(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Delete_Template", ReplyAction="http://tempuri.org/IDesktopEndpoint/Delete_TemplateResponse")]
        System.Threading.Tasks.Task<bool> Delete_TemplateAsync(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Update_Template", ReplyAction="http://tempuri.org/IDesktopEndpoint/Update_TemplateResponse")]
        bool Update_Template(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/Update_Template", ReplyAction="http://tempuri.org/IDesktopEndpoint/Update_TemplateResponse")]
        System.Threading.Tasks.Task<bool> Update_TemplateAsync(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/RandomID_Template", ReplyAction="http://tempuri.org/IDesktopEndpoint/RandomID_TemplateResponse")]
        string RandomID_Template();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesktopEndpoint/RandomID_Template", ReplyAction="http://tempuri.org/IDesktopEndpoint/RandomID_TemplateResponse")]
        System.Threading.Tasks.Task<string> RandomID_TemplateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDesktopEndpointChannel : SMS_Web_client.ServiceReference1.IDesktopEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DesktopEndpointClient : System.ServiceModel.ClientBase<SMS_Web_client.ServiceReference1.IDesktopEndpoint>, SMS_Web_client.ServiceReference1.IDesktopEndpoint {
        
        public DesktopEndpointClient() {
        }
        
        public DesktopEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DesktopEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesktopEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesktopEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Insert(SMS_Web_client.ServiceReference1.DTO_Account Account) {
            return base.Channel.Insert(Account);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAsync(SMS_Web_client.ServiceReference1.DTO_Account Account) {
            return base.Channel.InsertAsync(Account);
        }
        
        public bool Update(SMS_Web_client.ServiceReference1.DTO_Account Account) {
            return base.Channel.Update(Account);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(SMS_Web_client.ServiceReference1.DTO_Account Account) {
            return base.Channel.UpdateAsync(Account);
        }
        
        public string RandomID() {
            return base.Channel.RandomID();
        }
        
        public System.Threading.Tasks.Task<string> RandomIDAsync() {
            return base.Channel.RandomIDAsync();
        }
        
        public bool CheckSignin(string sql) {
            return base.Channel.CheckSignin(sql);
        }
        
        public System.Threading.Tasks.Task<bool> CheckSigninAsync(string sql) {
            return base.Channel.CheckSigninAsync(sql);
        }
        
        public string GetID(string sql) {
            return base.Channel.GetID(sql);
        }
        
        public System.Threading.Tasks.Task<string> GetIDAsync(string sql) {
            return base.Channel.GetIDAsync(sql);
        }
        
        public string GetName(string sql) {
            return base.Channel.GetName(sql);
        }
        
        public System.Threading.Tasks.Task<string> GetNameAsync(string sql) {
            return base.Channel.GetNameAsync(sql);
        }
        
        public SMS_Web_client.ServiceReference1.DTO_Customer[] load_Customer(string sql) {
            return base.Channel.load_Customer(sql);
        }
        
        public System.Threading.Tasks.Task<SMS_Web_client.ServiceReference1.DTO_Customer[]> load_CustomerAsync(string sql) {
            return base.Channel.load_CustomerAsync(sql);
        }
        
        public bool Insert_Customer(SMS_Web_client.ServiceReference1.DTO_Customer _Cus) {
            return base.Channel.Insert_Customer(_Cus);
        }
        
        public System.Threading.Tasks.Task<bool> Insert_CustomerAsync(SMS_Web_client.ServiceReference1.DTO_Customer _Cus) {
            return base.Channel.Insert_CustomerAsync(_Cus);
        }
        
        public bool Delete_Customer(SMS_Web_client.ServiceReference1.DTO_Customer _Cus) {
            return base.Channel.Delete_Customer(_Cus);
        }
        
        public System.Threading.Tasks.Task<bool> Delete_CustomerAsync(SMS_Web_client.ServiceReference1.DTO_Customer _Cus) {
            return base.Channel.Delete_CustomerAsync(_Cus);
        }
        
        public bool Update_Customer(SMS_Web_client.ServiceReference1.DTO_Customer _Cus) {
            return base.Channel.Update_Customer(_Cus);
        }
        
        public System.Threading.Tasks.Task<bool> Update_CustomerAsync(SMS_Web_client.ServiceReference1.DTO_Customer _Cus) {
            return base.Channel.Update_CustomerAsync(_Cus);
        }
        
        public string RandomID_Customer() {
            return base.Channel.RandomID_Customer();
        }
        
        public System.Threading.Tasks.Task<string> RandomID_CustomerAsync() {
            return base.Channel.RandomID_CustomerAsync();
        }
        
        public string SMSID() {
            return base.Channel.SMSID();
        }
        
        public System.Threading.Tasks.Task<string> SMSIDAsync() {
            return base.Channel.SMSIDAsync();
        }
        
        public bool SendSMS(SMS_Web_client.ServiceReference1.DTO_SMS sms) {
            return base.Channel.SendSMS(sms);
        }
        
        public System.Threading.Tasks.Task<bool> SendSMSAsync(SMS_Web_client.ServiceReference1.DTO_SMS sms) {
            return base.Channel.SendSMSAsync(sms);
        }
        
        public SMS_Web_client.ServiceReference1.DTO_Schedule[] Load_Schedule() {
            return base.Channel.Load_Schedule();
        }
        
        public System.Threading.Tasks.Task<SMS_Web_client.ServiceReference1.DTO_Schedule[]> Load_ScheduleAsync() {
            return base.Channel.Load_ScheduleAsync();
        }
        
        public bool Insert_Schedule(SMS_Web_client.ServiceReference1.DTO_Schedule _sch) {
            return base.Channel.Insert_Schedule(_sch);
        }
        
        public System.Threading.Tasks.Task<bool> Insert_ScheduleAsync(SMS_Web_client.ServiceReference1.DTO_Schedule _sch) {
            return base.Channel.Insert_ScheduleAsync(_sch);
        }
        
        public bool Delete_Schedule(SMS_Web_client.ServiceReference1.DTO_Schedule _sch) {
            return base.Channel.Delete_Schedule(_sch);
        }
        
        public System.Threading.Tasks.Task<bool> Delete_ScheduleAsync(SMS_Web_client.ServiceReference1.DTO_Schedule _sch) {
            return base.Channel.Delete_ScheduleAsync(_sch);
        }
        
        public bool Update_Schedule(SMS_Web_client.ServiceReference1.DTO_Schedule _sch) {
            return base.Channel.Update_Schedule(_sch);
        }
        
        public System.Threading.Tasks.Task<bool> Update_ScheduleAsync(SMS_Web_client.ServiceReference1.DTO_Schedule _sch) {
            return base.Channel.Update_ScheduleAsync(_sch);
        }
        
        public string RandomID_Schedule() {
            return base.Channel.RandomID_Schedule();
        }
        
        public System.Threading.Tasks.Task<string> RandomID_ScheduleAsync() {
            return base.Channel.RandomID_ScheduleAsync();
        }
        
        public SMS_Web_client.ServiceReference1.DTO_Group[] Load_Group(string sql) {
            return base.Channel.Load_Group(sql);
        }
        
        public System.Threading.Tasks.Task<SMS_Web_client.ServiceReference1.DTO_Group[]> Load_GroupAsync(string sql) {
            return base.Channel.Load_GroupAsync(sql);
        }
        
        public bool Insert_Group(SMS_Web_client.ServiceReference1.DTO_Group _group) {
            return base.Channel.Insert_Group(_group);
        }
        
        public System.Threading.Tasks.Task<bool> Insert_GroupAsync(SMS_Web_client.ServiceReference1.DTO_Group _group) {
            return base.Channel.Insert_GroupAsync(_group);
        }
        
        public bool Delete_Group(SMS_Web_client.ServiceReference1.DTO_Group _group) {
            return base.Channel.Delete_Group(_group);
        }
        
        public System.Threading.Tasks.Task<bool> Delete_GroupAsync(SMS_Web_client.ServiceReference1.DTO_Group _group) {
            return base.Channel.Delete_GroupAsync(_group);
        }
        
        public bool Update_Group(SMS_Web_client.ServiceReference1.DTO_Group _group) {
            return base.Channel.Update_Group(_group);
        }
        
        public System.Threading.Tasks.Task<bool> Update_GroupAsync(SMS_Web_client.ServiceReference1.DTO_Group _group) {
            return base.Channel.Update_GroupAsync(_group);
        }
        
        public string RandomID_Group() {
            return base.Channel.RandomID_Group();
        }
        
        public System.Threading.Tasks.Task<string> RandomID_GroupAsync() {
            return base.Channel.RandomID_GroupAsync();
        }
        
        public SMS_Web_client.ServiceReference1.DTO_SMS_Template[] Load_Template(string sql) {
            return base.Channel.Load_Template(sql);
        }
        
        public System.Threading.Tasks.Task<SMS_Web_client.ServiceReference1.DTO_SMS_Template[]> Load_TemplateAsync(string sql) {
            return base.Channel.Load_TemplateAsync(sql);
        }
        
        public bool Insert_Template(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp) {
            return base.Channel.Insert_Template(_temp);
        }
        
        public System.Threading.Tasks.Task<bool> Insert_TemplateAsync(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp) {
            return base.Channel.Insert_TemplateAsync(_temp);
        }
        
        public bool Delete_Template(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp) {
            return base.Channel.Delete_Template(_temp);
        }
        
        public System.Threading.Tasks.Task<bool> Delete_TemplateAsync(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp) {
            return base.Channel.Delete_TemplateAsync(_temp);
        }
        
        public bool Update_Template(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp) {
            return base.Channel.Update_Template(_temp);
        }
        
        public System.Threading.Tasks.Task<bool> Update_TemplateAsync(SMS_Web_client.ServiceReference1.DTO_SMS_Template _temp) {
            return base.Channel.Update_TemplateAsync(_temp);
        }
        
        public string RandomID_Template() {
            return base.Channel.RandomID_Template();
        }
        
        public System.Threading.Tasks.Task<string> RandomID_TemplateAsync() {
            return base.Channel.RandomID_TemplateAsync();
        }
    }
}
